from fpdf import FPDF

class InvoicePDF(FPDF):
    def header(self):
        #Company Name & Address
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, 'Your Company', 0, 1, 'C')
        self.set_font('Arial', '', 10)
        self.cell(0, 10, 'Your Company Address', 0, 1, 'C')
        self.cell(0, 10, 'Phone: (000) 000-0000 | Email: info@yourcompany.com', 0, 1, 'C')
        self.ln(10)
    
    def invoice_info(self, invoice_number, invoice_date, due_date):
        #Invoice details
        self.set_font('Arial', '', 10)
        self.cell(100, 10, f'Invoice Number: {invoice_number}', 0, 0)
        self.cell(0, 10, f'Invoice Date: {invoice_date}', 0, 1)
        self.cell(100, 10, f'Due Date: {due_date}', 0, 1)
        self.ln(10)

    def bill_to(self, customer_name, customer_address):
        #Customer details
        self.set_font('Arial', 'B', 10)
        self.cell(0, 10, 'Bill To:', 0, 1)
        self.set_font('Arial', '', 10)
        self.cell(0, 10, customer_name, 0, 1)
        self.cell(0, 10, customer_address, 0, 1)
        self.ln(10)

    def itemized_list(self, items):
        #Table header
        self.set_font('Arial', 'B', 10)
        self.cell(80, 10, 'Description', 1)
        self.cell(30, 10, 'Quantity', 1)
        self.cell(30, 10, 'Unit Price', 1)
        self.cell(30, 10, 'Total Price', 1)
        self.ln()
        #Table rows
        self.set_font('Arial', '', 10)
        for item in items:
            self.cell(80, 10, item['description'], 1)
            self.cell(30, 10, str(item['quantity']), 1)
            self.cell(30, 10, f"${item['unit_price']:.2f}", 1)
            self.cell(30, 10, f"${item['total_price']:.2f}", 1)
            self.ln()

    def summary(self, subtotal, tax, total):
        #Summary
        self.set_font('Arial', '', 10)
        self.cell(0, 10, '', 0, 1)
        self.cell(110, 10, '', 0)
        self.cell(30, 10, 'Subtotal', 1)
        self.cell(30, 10, f"${subtotal:.2f}", 1, 1)
        self.cell(110, 10, '', 0)
        self.cell(30, 10, 'Tax', 1)
        self.cell(30, 10, f"${tax:.2f}", 1, 1)
        self.cell(110, 10, '', 0)
        self.cell(30, 10, 'Total', 1)
        self.cell(30, 10, f"${total:.2f}", 1, 1)

    def footer(self):
        #Footer with payment & notes
        self.set_y(-50)
        self.set_font('Arial', 'I', 10)
        self.multi_cell(0, 10, "Payment Terms: Please pay within 30 days.")
        self.set_font('Arial', '', 8)
        self.cell(0, 10, 'Generated by Your Company Name', 0, 1, 'C')

#Sample data
invoice_number = '001'
invoice_date = '18/06/2024'
due_date = '18/07/2024'
customer_name = 'John Doe'
customer_address = '1234 Elm Street, USA'
items = [
    {'description': 'Product 1', 'quantity': 2, 'unit_price': 50.00, 'total_price': 100.00},
    {'description': 'Product 2', 'quantity': 1, 'unit_price': 150.00, 'total_price': 150.00},
]
subtotal = sum(item['total_price'] for item in items)
tax = subtotal * 0.07
total = subtotal + tax

#Generate PDF
pdf = InvoicePDF()
pdf.add_page()
pdf.invoice_info(invoice_number, invoice_date, due_date)
pdf.bill_to(customer_name, customer_address)
pdf.itemized_list(items)
pdf.summary(subtotal, tax, total)
pdf.footer()

#Save PDF to a file
pdf_file_path = 'invoice.pdf'
pdf.output(pdf_file_path)
